#command to run the yaml: docker compose -p aira_backend up -d
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - aira_postgres_data:/var/lib/postgresql/data # Use the named volume
      - ./sql:/docker-entrypoint-initdb.d # Mount the sql directory
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW}
    ports:
      - "5050:80"
    depends_on:
      - postgres
      
  fastapi:
    build: ./fastapi
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PW}@postgres:5432/${POSTGRES_DB}
      - PORT=8000

volumes:
  aira_postgres_data: # Define the named volume explicitly
    name: aira # Optional: Explicitly set the volume name on the host